apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "remediator.clusterRoleName" . }}
  labels:
    {{- include "remediator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
{{- if .Values.parity.readonly }}
    verbs: ["get", "list", "watch"]
{{- else }}
    verbs: ["*"]
{{- end }}