apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "remediator.clusterRoleName" . }}-binding
  labels:
    {{- include "remediator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "remediator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "remediator.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io