apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "remediator.serviceAccountName" . }}-cluster-role-binding
  labels:
    {{- include "remediator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "remediator.serviceAccountName" . }}
  namespace: {{ .Values.parity.namespace }}
roleRef:
  kind: ClusterRole
  name: parity-cluster-role
  apiGroup: rbac.authorization.k8s.io