apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "remediator.fullname" . }}
  labels:
    {{- include "remediator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "remediator.selectorLabels" . | nindent 6 }}
  egress:
  - to:
    - ipBlock:
        cidr: 34.168.135.128/32 ## remediator.api.tryparity.com
    ports:
    - protocol: TCP
      port: 443
  policyTypes:
  - Egress