apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "remediator.serviceAccountName" . }}
  labels:
    {{- include "remediator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
